import NextAuth from "next-auth";
import { authOptions } from "./authOptions";

const handler = NextAuth(authOptions);

export { handler as GET, handler as POST };
// Be sure to add the following to your .env.local:
// NEXTAUTH_SECRET=your-secret-key-here
// GITHUB_ID=...
// GITHUB_SECRET=...
// GOOGLE_CLIENT_ID=...
// GOOGLE_CLIENT_SECRET=...
// AZURE_AD_CLIENT_ID=...
// AZURE_AD_CLIENT_SECRET=...
// AZURE_AD_TENANT_ID=... 